baseURL = 'https://b.cmrt.dev/'
languageCode = 'en-gb'
title = 'How to fail at brevity'
theme = ['PaperMod', 'hugo-admonitions']

buildDrafts = false
buildFuture = false
buildExpired = false
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[minify]
  disableXML = true
  minifyOutput = false

[params]
  # https://github.com/adityatelange/hugo-PaperMod/wiki/Variables
  comments = false
  disableSpecial1stPost = false
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowPostNavLinks = false
  ShowReadingTime = true  
  ShowRssButtonInSectionTermList = true
  ShowWordCount = true  
  showtoc = true
  tocopen = true
  UseHugoToc = true
  # Currently unused
  # description = "ExampleSite description"
  # keywords = [ "Blog", "Portfolio", "PaperMod" ]
  # author = "Me"
  # images = [ "<link or path of image for opengraph, twitter-cards>" ]
  # DateFormat = "January 2, 2006"

[params.assets]
# disableFingerprinting: true
  disableHLJS = true

  apple_touch_icon = '/apple-touch-icon.png'
  favicon = '/favicon.ico'
  favicon16x16 = '/favicon-16x16.png'
  favicon32x32 = '/favicon-32x32.png'
  safari_pinned_tab = '/safari-pinned-tab.png'

# [analytics.google]
#   SiteVerificationTag = "XYZabc"

# Menu items
[[menu.main]]
  identifier = "archives"
  name = "Archive"
  url = "/archives/"
  weight = 10

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 20

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
    # noClasses = false
    # Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

[sitemap]
  disable = false
  filename = 'sitemap.xml'
  priority = -1

# For Search
[outputs]
  home =[ "html", "rss", "json" ]    
[fuseOpts]
  distance = 1000
  isCaseSensitive = false
  keys = ["title", "permalink", "summary", "content"]
  limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
  location = 0
  minMatchCharLength = 0
  shouldSort = true
  threshold = 0.4